[book]
title = "DFPS Documentation"
authors = ["DFPS Team"]
language = "en"
multilingual = false
src = "src"

[build]
create-missing = true

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/JonTDean/depth_forward_platonic_space-clinical_model"
